// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class FloatValue {
  static encode(message: FloatValue, writer: Writer): void {
    writer.uint32(13);
    writer.float(message.value);
  }

  static decode(reader: Reader, length: i32): FloatValue {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new FloatValue();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value = reader.float();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: f32;

  constructor(value: f32 = 0.0) {
    this.value = value;
  }
}

export function encodeFloatValue(message: FloatValue): Uint8Array {
  return Protobuf.encode(message, FloatValue.encode);
}

export function decodeFloatValue(buffer: Uint8Array): FloatValue {
  return Protobuf.decode<FloatValue>(buffer, FloatValue.decode);
}
