// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class Int64Value {
  static encode(message: Int64Value, writer: Writer): void {
    writer.uint32(8);
    writer.int64(message.value);
  }

  static decode(reader: Reader, length: i32): Int64Value {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Int64Value();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: i64;

  constructor(value: i64 = 0) {
    this.value = value;
  }
}

export function encodeInt64Value(message: Int64Value): Uint8Array {
  return Protobuf.encode(message, Int64Value.encode);
}

export function decodeInt64Value(buffer: Uint8Array): Int64Value {
  return Protobuf.decode<Int64Value>(buffer, Int64Value.decode);
}
