// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class UInt32Value {
  static encode(message: UInt32Value, writer: Writer): void {
    writer.uint32(8);
    writer.uint32(message.value);
  }

  static decode(reader: Reader, length: i32): UInt32Value {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new UInt32Value();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value = reader.uint32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: u32;

  constructor(value: u32 = 0) {
    this.value = value;
  }
}

export function encodeUInt32Value(message: UInt32Value): Uint8Array {
  return Protobuf.encode(message, UInt32Value.encode);
}

export function decodeUInt32Value(buffer: Uint8Array): UInt32Value {
  return Protobuf.decode<UInt32Value>(buffer, UInt32Value.decode);
}
