// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class Addresses {
  static encode(message: Addresses, writer: Writer): void {
    const addresses = message.addresses;
    if (addresses.length !== 0) {
      for (let i: i32 = 0; i < addresses.length; ++i) {
        writer.uint32(10);
        writer.string(addresses[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): Addresses {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Addresses();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.addresses.push(reader.string());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  addresses: Array<string>;

  constructor(addresses: Array<string> = []) {
    this.addresses = addresses;
  }
}

export function encodeAddresses(message: Addresses): Uint8Array {
  return Protobuf.encode(message, Addresses.encode);
}

export function decodeAddresses(buffer: Uint8Array): Addresses {
  return Protobuf.decode<Addresses>(buffer, Addresses.decode);
}
