// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

export enum AddressCategory {
  ADDRESS_CATEGORY_UNSPECIFIED = 0,
  ADDRESS_CATEGORY_USER_ADDRESS = 1,
  ADDRESS_CATEGORY_SC_ADDRESS = 2,
}
