// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class BytesMapFieldEntry {
  static encode(message: BytesMapFieldEntry, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.key);

    writer.uint32(18);
    writer.bytes(message.value);
  }

  static decode(reader: Reader, length: i32): BytesMapFieldEntry {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BytesMapFieldEntry();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.key = reader.bytes();
          break;

        case 2:
          message.value = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  key: Uint8Array;
  value: Uint8Array;

  constructor(
    key: Uint8Array = new Uint8Array(0),
    value: Uint8Array = new Uint8Array(0)
  ) {
    this.key = key;
    this.value = value;
  }
}

export function encodeBytesMapFieldEntry(
  message: BytesMapFieldEntry
): Uint8Array {
  return Protobuf.encode(message, BytesMapFieldEntry.encode);
}

export function decodeBytesMapFieldEntry(
  buffer: Uint8Array
): BytesMapFieldEntry {
  return Protobuf.decode<BytesMapFieldEntry>(buffer, BytesMapFieldEntry.decode);
}
