// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

export enum ComparisonResult {
  COMPARISON_RESULT_UNSPECIFIED = 0,
  COMPARISON_RESULT_LOWER = 1,
  COMPARISON_RESULT_EQUAL = 2,
  COMPARISON_RESULT_GREATER = 3,
}
