// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class Error {
  static encode(message: Error, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.code);

    writer.uint32(18);
    writer.string(message.message);
  }

  static decode(reader: Reader, length: i32): Error {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Error();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.code = reader.int32();
          break;

        case 2:
          message.message = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  code: i32;
  message: string;

  constructor(code: i32 = 0, message: string = "") {
    this.code = code;
    this.message = message;
  }
}

export function encodeError(message: Error): Uint8Array {
  return Protobuf.encode(message, Error.encode);
}

export function decodeError(buffer: Uint8Array): Error {
  return Protobuf.decode<Error>(buffer, Error.decode);
}
