// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class NativeTime {
  static encode(message: NativeTime, writer: Writer): void {
    writer.uint32(9);
    writer.fixed64(message.milliseconds);
  }

  static decode(reader: Reader, length: i32): NativeTime {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NativeTime();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.milliseconds = reader.fixed64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  milliseconds: i64;

  constructor(milliseconds: i64 = 0) {
    this.milliseconds = milliseconds;
  }
}

export function encodeNativeTime(message: NativeTime): Uint8Array {
  return Protobuf.encode(message, NativeTime.encode);
}

export function decodeNativeTime(buffer: Uint8Array): NativeTime {
  return Protobuf.decode<NativeTime>(buffer, NativeTime.decode);
}
