// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class AddressFromPubKeyRequest {
  static encode(message: AddressFromPubKeyRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.pubKey);
  }

  static decode(reader: Reader, length: i32): AddressFromPubKeyRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AddressFromPubKeyRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.pubKey = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  pubKey: string;

  constructor(pubKey: string = "") {
    this.pubKey = pubKey;
  }
}

export function encodeAddressFromPubKeyRequest(
  message: AddressFromPubKeyRequest
): Uint8Array {
  return Protobuf.encode(message, AddressFromPubKeyRequest.encode);
}

export function decodeAddressFromPubKeyRequest(
  buffer: Uint8Array
): AddressFromPubKeyRequest {
  return Protobuf.decode<AddressFromPubKeyRequest>(
    buffer,
    AddressFromPubKeyRequest.decode
  );
}
