// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class Amount {
  static encode(message: Amount, writer: Writer): void {
    writer.uint32(9);
    writer.fixed64(message.amount);
  }

  static decode(reader: Reader, length: i32): Amount {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Amount();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.amount = reader.fixed64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  amount: i64;

  constructor(amount: i64 = 0) {
    this.amount = amount;
  }
}

export function encodeAmount(message: Amount): Uint8Array {
  return Protobuf.encode(message, Amount.encode);
}

export function decodeAmount(buffer: Uint8Array): Amount {
  return Protobuf.decode<Amount>(buffer, Amount.decode);
}
