// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class AppendDataForResult {
  static encode(message: AppendDataForResult, writer: Writer): void {}

  static decode(reader: Reader, length: i32): AppendDataForResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AppendDataForResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeAppendDataForResult(
  message: AppendDataForResult
): Uint8Array {
  return Protobuf.encode(message, AppendDataForResult.encode);
}

export function decodeAppendDataForResult(
  buffer: Uint8Array
): AppendDataForResult {
  return Protobuf.decode<AppendDataForResult>(
    buffer,
    AppendDataForResult.decode
  );
}
