// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class AppendDsValueResult {
  static encode(message: AppendDsValueResult, writer: Writer): void {}

  static decode(reader: Reader, length: i32): AppendDsValueResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AppendDsValueResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeAppendDsValueResult(
  message: AppendDsValueResult
): Uint8Array {
  return Protobuf.encode(message, AppendDsValueResult.encode);
}

export function decodeAppendDsValueResult(
  buffer: Uint8Array
): AppendDsValueResult {
  return Protobuf.decode<AppendDsValueResult>(
    buffer,
    AppendDsValueResult.decode
  );
}
