// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class Blake3HashResult {
  static encode(message: Blake3HashResult, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.hash);
  }

  static decode(reader: Reader, length: i32): Blake3HashResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Blake3HashResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.hash = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  hash: Uint8Array;

  constructor(hash: Uint8Array = new Uint8Array(0)) {
    this.hash = hash;
  }
}

export function encodeBlake3HashResult(message: Blake3HashResult): Uint8Array {
  return Protobuf.encode(message, Blake3HashResult.encode);
}

export function decodeBlake3HashResult(buffer: Uint8Array): Blake3HashResult {
  return Protobuf.decode<Blake3HashResult>(buffer, Blake3HashResult.decode);
}
