// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class ChainIdRequest {
  static encode(message: ChainIdRequest, writer: Writer): void {}

  static decode(reader: Reader, length: i32): ChainIdRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChainIdRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeChainIdRequest(message: ChainIdRequest): Uint8Array {
  return Protobuf.encode(message, ChainIdRequest.encode);
}

export function decodeChainIdRequest(buffer: Uint8Array): ChainIdRequest {
  return Protobuf.decode<ChainIdRequest>(buffer, ChainIdRequest.decode);
}
