// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class ChainIdResult {
  static encode(message: ChainIdResult, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.id);
  }

  static decode(reader: Reader, length: i32): ChainIdResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ChainIdResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: u64;

  constructor(id: u64 = 0) {
    this.id = id;
  }
}

export function encodeChainIdResult(message: ChainIdResult): Uint8Array {
  return Protobuf.encode(message, ChainIdResult.encode);
}

export function decodeChainIdResult(buffer: Uint8Array): ChainIdResult {
  return Protobuf.decode<ChainIdResult>(buffer, ChainIdResult.decode);
}
