// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativeTime } from "../../model/v1/NativeTime";

export class CheckedAddNativeTimeResult {
  static encode(message: CheckedAddNativeTimeResult, writer: Writer): void {
    const sum = message.sum;
    if (sum !== null) {
      writer.uint32(10);
      writer.fork();
      NativeTime.encode(sum, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CheckedAddNativeTimeResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CheckedAddNativeTimeResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.sum = NativeTime.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  sum: NativeTime | null;

  constructor(sum: NativeTime | null = null) {
    this.sum = sum;
  }
}

export function encodeCheckedAddNativeTimeResult(
  message: CheckedAddNativeTimeResult
): Uint8Array {
  return Protobuf.encode(message, CheckedAddNativeTimeResult.encode);
}

export function decodeCheckedAddNativeTimeResult(
  buffer: Uint8Array
): CheckedAddNativeTimeResult {
  return Protobuf.decode<CheckedAddNativeTimeResult>(
    buffer,
    CheckedAddNativeTimeResult.decode
  );
}
