// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class CheckNativePubKeyResult {
  static encode(message: CheckNativePubKeyResult, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.isValid);
  }

  static decode(reader: Reader, length: i32): CheckNativePubKeyResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CheckNativePubKeyResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.isValid = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  isValid: bool;

  constructor(isValid: bool = false) {
    this.isValid = isValid;
  }
}

export function encodeCheckNativePubKeyResult(
  message: CheckNativePubKeyResult
): Uint8Array {
  return Protobuf.encode(message, CheckNativePubKeyResult.encode);
}

export function decodeCheckNativePubKeyResult(
  buffer: Uint8Array
): CheckNativePubKeyResult {
  return Protobuf.decode<CheckNativePubKeyResult>(
    buffer,
    CheckNativePubKeyResult.decode
  );
}
