// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class CheckAddressRequest {
  static encode(message: CheckAddressRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.toCheck);
  }

  static decode(reader: Reader, length: i32): CheckAddressRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CheckAddressRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.toCheck = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  toCheck: string;

  constructor(toCheck: string = "") {
    this.toCheck = toCheck;
  }
}

export function encodeCheckAddressRequest(
  message: CheckAddressRequest
): Uint8Array {
  return Protobuf.encode(message, CheckAddressRequest.encode);
}

export function decodeCheckAddressRequest(
  buffer: Uint8Array
): CheckAddressRequest {
  return Protobuf.decode<CheckAddressRequest>(
    buffer,
    CheckAddressRequest.decode
  );
}
