// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class CheckSigRequest {
  static encode(message: CheckSigRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.toCheck);
  }

  static decode(reader: Reader, length: i32): CheckSigRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CheckSigRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.toCheck = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  toCheck: string;

  constructor(toCheck: string = "") {
    this.toCheck = toCheck;
  }
}

export function encodeCheckSigRequest(message: CheckSigRequest): Uint8Array {
  return Protobuf.encode(message, CheckSigRequest.encode);
}

export function decodeCheckSigRequest(buffer: Uint8Array): CheckSigRequest {
  return Protobuf.decode<CheckSigRequest>(buffer, CheckSigRequest.decode);
}
