// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativeHash } from "..\\..\\model\\v1\\NativeHash";

export class CheckNativeHashRequest {
  static encode(message: CheckNativeHashRequest, writer: Writer): void {
    const toCheck = message.toCheck;
    if (toCheck !== null) {
      writer.uint32(10);
      writer.fork();
      NativeHash.encode(toCheck, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CheckNativeHashRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CheckNativeHashRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.toCheck = NativeHash.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  toCheck: NativeHash | null;

  constructor(toCheck: NativeHash | null = null) {
    this.toCheck = toCheck;
  }
}

export function encodeCheckNativeHashRequest(
  message: CheckNativeHashRequest
): Uint8Array {
  return Protobuf.encode(message, CheckNativeHashRequest.encode);
}

export function decodeCheckNativeHashRequest(
  buffer: Uint8Array
): CheckNativeHashRequest {
  return Protobuf.decode<CheckNativeHashRequest>(
    buffer,
    CheckNativeHashRequest.decode
  );
}
