// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativePubKey } from "..\\..\\model\\v1\\NativePubKey";

export class CheckNativePubKeyRequest {
  static encode(message: CheckNativePubKeyRequest, writer: Writer): void {
    const toCheck = message.toCheck;
    if (toCheck !== null) {
      writer.uint32(10);
      writer.fork();
      NativePubKey.encode(toCheck, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CheckNativePubKeyRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CheckNativePubKeyRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.toCheck = NativePubKey.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  toCheck: NativePubKey | null;

  constructor(toCheck: NativePubKey | null = null) {
    this.toCheck = toCheck;
  }
}

export function encodeCheckNativePubKeyRequest(
  message: CheckNativePubKeyRequest
): Uint8Array {
  return Protobuf.encode(message, CheckNativePubKeyRequest.encode);
}

export function decodeCheckNativePubKeyRequest(
  buffer: Uint8Array
): CheckNativePubKeyRequest {
  return Protobuf.decode<CheckNativePubKeyRequest>(
    buffer,
    CheckNativePubKeyRequest.decode
  );
}
