// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativeTime } from "../../model/v1/NativeTime";
import { UInt64Value } from "../../../google/protobuf/UInt64Value";

export class CheckedMulNativeTimeRequest {
  static encode(message: CheckedMulNativeTimeRequest, writer: Writer): void {
    const time = message.time;
    if (time !== null) {
      writer.uint32(10);
      writer.fork();
      NativeTime.encode(time, writer);
      writer.ldelim();
    }

    const mandatoryCoefficient = message.mandatoryCoefficient;
    if (mandatoryCoefficient !== null) {
      writer.uint32(18);
      writer.fork();
      UInt64Value.encode(mandatoryCoefficient, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CheckedMulNativeTimeRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CheckedMulNativeTimeRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.time = NativeTime.decode(reader, reader.uint32());
          break;

        case 2:
          message.mandatoryCoefficient = UInt64Value.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  time: NativeTime | null;
  mandatoryCoefficient: UInt64Value | null;

  constructor(
    time: NativeTime | null = null,
    mandatoryCoefficient: UInt64Value | null = null
  ) {
    this.time = time;
    this.mandatoryCoefficient = mandatoryCoefficient;
  }
}

export function encodeCheckedMulNativeTimeRequest(
  message: CheckedMulNativeTimeRequest
): Uint8Array {
  return Protobuf.encode(message, CheckedMulNativeTimeRequest.encode);
}

export function decodeCheckedMulNativeTimeRequest(
  buffer: Uint8Array
): CheckedMulNativeTimeRequest {
  return Protobuf.decode<CheckedMulNativeTimeRequest>(
    buffer,
    CheckedMulNativeTimeRequest.decode
  );
}
