// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class CheckBlake3HashResult {
  static encode(message: CheckBlake3HashResult, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.isValid);
  }

  static decode(reader: Reader, length: i32): CheckBlake3HashResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CheckBlake3HashResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.isValid = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  isValid: bool;

  constructor(isValid: bool = false) {
    this.isValid = isValid;
  }
}

export function encodeCheckBlake3HashResult(
  message: CheckBlake3HashResult
): Uint8Array {
  return Protobuf.encode(message, CheckBlake3HashResult.encode);
}

export function decodeCheckBlake3HashResult(
  buffer: Uint8Array
): CheckBlake3HashResult {
  return Protobuf.decode<CheckBlake3HashResult>(
    buffer,
    CheckBlake3HashResult.decode
  );
}
