// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativeAmount } from "..\\..\\model\\v1\\NativeAmount";

export class CheckNativeAmountRequest {
  static encode(message: CheckNativeAmountRequest, writer: Writer): void {
    const toCheck = message.toCheck;
    if (toCheck !== null) {
      writer.uint32(10);
      writer.fork();
      NativeAmount.encode(toCheck, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CheckNativeAmountRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CheckNativeAmountRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.toCheck = NativeAmount.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  toCheck: NativeAmount | null;

  constructor(toCheck: NativeAmount | null = null) {
    this.toCheck = toCheck;
  }
}

export function encodeCheckNativeAmountRequest(
  message: CheckNativeAmountRequest
): Uint8Array {
  return Protobuf.encode(message, CheckNativeAmountRequest.encode);
}

export function decodeCheckNativeAmountRequest(
  buffer: Uint8Array
): CheckNativeAmountRequest {
  return Protobuf.decode<CheckNativeAmountRequest>(
    buffer,
    CheckNativeAmountRequest.decode
  );
}
