// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativeTime } from "../../model/v1/NativeTime";

export class CheckedScalarMulNativeTimeResult {
  static encode(
    message: CheckedScalarMulNativeTimeResult,
    writer: Writer
  ): void {
    const product = message.product;
    if (product !== null) {
      writer.uint32(10);
      writer.fork();
      NativeTime.encode(product, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CheckedScalarMulNativeTimeResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CheckedScalarMulNativeTimeResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.product = NativeTime.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  product: NativeTime | null;

  constructor(product: NativeTime | null = null) {
    this.product = product;
  }
}

export function encodeCheckedScalarMulNativeTimeResult(
  message: CheckedScalarMulNativeTimeResult
): Uint8Array {
  return Protobuf.encode(message, CheckedScalarMulNativeTimeResult.encode);
}

export function decodeCheckedScalarMulNativeTimeResult(
  buffer: Uint8Array
): CheckedScalarMulNativeTimeResult {
  return Protobuf.decode<CheckedScalarMulNativeTimeResult>(
    buffer,
    CheckedScalarMulNativeTimeResult.decode
  );
}
