// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class ComparePubKeyRequest {
  static encode(message: ComparePubKeyRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.left);

    writer.uint32(18);
    writer.string(message.right);
  }

  static decode(reader: Reader, length: i32): ComparePubKeyRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ComparePubKeyRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.left = reader.string();
          break;

        case 2:
          message.right = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  left: string;
  right: string;

  constructor(left: string = "", right: string = "") {
    this.left = left;
    this.right = right;
  }
}

export function encodeComparePubKeyRequest(
  message: ComparePubKeyRequest
): Uint8Array {
  return Protobuf.encode(message, ComparePubKeyRequest.encode);
}

export function decodeComparePubKeyRequest(
  buffer: Uint8Array
): ComparePubKeyRequest {
  return Protobuf.decode<ComparePubKeyRequest>(
    buffer,
    ComparePubKeyRequest.decode
  );
}
