// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { ComparisonResult } from "../../model/v1/ComparisonResult";

export class CompareSigResult {
  static encode(message: CompareSigResult, writer: Writer): void {
    const result = message.result;
    if (result !== null) {
      writer.uint32(10);
      writer.fork();
      ComparisonResult.encode(result, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): CompareSigResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CompareSigResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.result = ComparisonResult.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  result: ComparisonResult | null;

  constructor(result: ComparisonResult | null = null) {
    this.result = result;
  }
}

export function encodeCompareSigResult(message: CompareSigResult): Uint8Array {
  return Protobuf.encode(message, CompareSigResult.encode);
}

export function decodeCompareSigResult(buffer: Uint8Array): CompareSigResult {
  return Protobuf.decode<CompareSigResult>(buffer, CompareSigResult.decode);
}
