// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class ConsolePutRequest {
  static encode(message: ConsolePutRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.message);
  }

  static decode(reader: Reader, length: i32): ConsolePutRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ConsolePutRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.message = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  message: string;

  constructor(message: string = "") {
    this.message = message;
  }
}

export function encodeConsolePutRequest(
  message: ConsolePutRequest
): Uint8Array {
  return Protobuf.encode(message, ConsolePutRequest.encode);
}

export function decodeConsolePutRequest(buffer: Uint8Array): ConsolePutRequest {
  return Protobuf.decode<ConsolePutRequest>(buffer, ConsolePutRequest.decode);
}
