// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class CreateScResult {
  static encode(message: CreateScResult, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.scAddress);
  }

  static decode(reader: Reader, length: i32): CreateScResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CreateScResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.scAddress = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  scAddress: string;

  constructor(scAddress: string = "") {
    this.scAddress = scAddress;
  }
}

export function encodeCreateScResult(message: CreateScResult): Uint8Array {
  return Protobuf.encode(message, CreateScResult.encode);
}

export function decodeCreateScResult(buffer: Uint8Array): CreateScResult {
  return Protobuf.decode<CreateScResult>(buffer, CreateScResult.decode);
}
