// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class CreateScRequest {
  static encode(message: CreateScRequest, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.bytecode);
  }

  static decode(reader: Reader, length: i32): CreateScRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CreateScRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.bytecode = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  bytecode: Uint8Array;

  constructor(bytecode: Uint8Array = new Uint8Array(0)) {
    this.bytecode = bytecode;
  }
}

export function encodeCreateScRequest(message: CreateScRequest): Uint8Array {
  return Protobuf.encode(message, CreateScRequest.encode);
}

export function decodeCreateScRequest(buffer: Uint8Array): CreateScRequest {
  return Protobuf.decode<CreateScRequest>(buffer, CreateScRequest.decode);
}
