// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class DateNowResult {
  static encode(message: DateNowResult, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.dateNow);
  }

  static decode(reader: Reader, length: i32): DateNowResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DateNowResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.dateNow = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  dateNow: u64;

  constructor(dateNow: u64 = 0) {
    this.dateNow = dateNow;
  }
}

export function encodeDateNowResult(message: DateNowResult): Uint8Array {
  return Protobuf.encode(message, DateNowResult.encode);
}

export function decodeDateNowResult(buffer: Uint8Array): DateNowResult {
  return Protobuf.decode<DateNowResult>(buffer, DateNowResult.decode);
}
