// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class DeferredCallExistsResult {
  static encode(message: DeferredCallExistsResult, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.callExists);
  }

  static decode(reader: Reader, length: i32): DeferredCallExistsResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DeferredCallExistsResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.callExists = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  callExists: bool;

  constructor(callExists: bool = false) {
    this.callExists = callExists;
  }
}

export function encodeDeferredCallExistsResult(
  message: DeferredCallExistsResult
): Uint8Array {
  return Protobuf.encode(message, DeferredCallExistsResult.encode);
}

export function decodeDeferredCallExistsResult(
  buffer: Uint8Array
): DeferredCallExistsResult {
  return Protobuf.decode<DeferredCallExistsResult>(
    buffer,
    DeferredCallExistsResult.decode
  );
}
