// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Slot } from "../../model/v1/Slot";

export class DeferredCallRegisterRequest {
  static encode(message: DeferredCallRegisterRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.targetAddress);

    writer.uint32(18);
    writer.string(message.targetFunction);

    const targetSlot = message.targetSlot;
    if (targetSlot !== null) {
      writer.uint32(26);
      writer.fork();
      Slot.encode(targetSlot, writer);
      writer.ldelim();
    }

    writer.uint32(32);
    writer.uint64(message.maxGas);

    writer.uint32(42);
    writer.bytes(message.params);

    writer.uint32(48);
    writer.uint64(message.coins);
  }

  static decode(reader: Reader, length: i32): DeferredCallRegisterRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DeferredCallRegisterRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.targetAddress = reader.string();
          break;

        case 2:
          message.targetFunction = reader.string();
          break;

        case 3:
          message.targetSlot = Slot.decode(reader, reader.uint32());
          break;

        case 4:
          message.maxGas = reader.uint64();
          break;

        case 5:
          message.params = reader.bytes();
          break;

        case 6:
          message.coins = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  targetAddress: string;
  targetFunction: string;
  targetSlot: Slot | null;
  maxGas: u64;
  params: Uint8Array;
  coins: u64;

  constructor(
    targetAddress: string = "",
    targetFunction: string = "",
    targetSlot: Slot | null = null,
    maxGas: u64 = 0,
    params: Uint8Array = new Uint8Array(0),
    coins: u64 = 0
  ) {
    this.targetAddress = targetAddress;
    this.targetFunction = targetFunction;
    this.targetSlot = targetSlot;
    this.maxGas = maxGas;
    this.params = params;
    this.coins = coins;
  }
}

export function encodeDeferredCallRegisterRequest(
  message: DeferredCallRegisterRequest
): Uint8Array {
  return Protobuf.encode(message, DeferredCallRegisterRequest.encode);
}

export function decodeDeferredCallRegisterRequest(
  buffer: Uint8Array
): DeferredCallRegisterRequest {
  return Protobuf.decode<DeferredCallRegisterRequest>(
    buffer,
    DeferredCallRegisterRequest.decode
  );
}
