// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { StringValue } from "../../../google/protobuf/StringValue";

export class DeferredCallCancelRequest {
  static encode(message: DeferredCallCancelRequest, writer: Writer): void {
    const callId = message.callId;
    if (callId !== null) {
      writer.uint32(10);
      writer.fork();
      StringValue.encode(callId, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): DeferredCallCancelRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DeferredCallCancelRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.callId = StringValue.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  callId: StringValue | null;

  constructor(callId: StringValue | null = null) {
    this.callId = callId;
  }
}

export function encodeDeferredCallCancelRequest(
  message: DeferredCallCancelRequest
): Uint8Array {
  return Protobuf.encode(message, DeferredCallCancelRequest.encode);
}

export function decodeDeferredCallCancelRequest(
  buffer: Uint8Array
): DeferredCallCancelRequest {
  return Protobuf.decode<DeferredCallCancelRequest>(
    buffer,
    DeferredCallCancelRequest.decode
  );
}
