// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class DeferredCallQuoteResult {
  static encode(message: DeferredCallQuoteResult, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.available);

    writer.uint32(16);
    writer.uint64(message.cost);
  }

  static decode(reader: Reader, length: i32): DeferredCallQuoteResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DeferredCallQuoteResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.available = reader.bool();
          break;

        case 2:
          message.cost = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  available: bool;
  cost: u64;

  constructor(available: bool = false, cost: u64 = 0) {
    this.available = available;
    this.cost = cost;
  }
}

export function encodeDeferredCallQuoteResult(
  message: DeferredCallQuoteResult
): Uint8Array {
  return Protobuf.encode(message, DeferredCallQuoteResult.encode);
}

export function decodeDeferredCallQuoteResult(
  buffer: Uint8Array
): DeferredCallQuoteResult {
  return Protobuf.decode<DeferredCallQuoteResult>(
    buffer,
    DeferredCallQuoteResult.decode
  );
}
