// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativeAmount } from "../../model/v1/NativeAmount";

export class DivRemNativeAmountRequest {
  static encode(message: DivRemNativeAmountRequest, writer: Writer): void {
    const dividend = message.dividend;
    if (dividend !== null) {
      writer.uint32(10);
      writer.fork();
      NativeAmount.encode(dividend, writer);
      writer.ldelim();
    }

    const divisor = message.divisor;
    if (divisor !== null) {
      writer.uint32(18);
      writer.fork();
      NativeAmount.encode(divisor, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): DivRemNativeAmountRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DivRemNativeAmountRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.dividend = NativeAmount.decode(reader, reader.uint32());
          break;

        case 2:
          message.divisor = NativeAmount.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  dividend: NativeAmount | null;
  divisor: NativeAmount | null;

  constructor(
    dividend: NativeAmount | null = null,
    divisor: NativeAmount | null = null
  ) {
    this.dividend = dividend;
    this.divisor = divisor;
  }
}

export function encodeDivRemNativeAmountRequest(
  message: DivRemNativeAmountRequest
): Uint8Array {
  return Protobuf.encode(message, DivRemNativeAmountRequest.encode);
}

export function decodeDivRemNativeAmountRequest(
  buffer: Uint8Array
): DivRemNativeAmountRequest {
  return Protobuf.decode<DivRemNativeAmountRequest>(
    buffer,
    DivRemNativeAmountRequest.decode
  );
}
