// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativeAmount } from "../../model/v1/NativeAmount";

export class DivRemNativeAmountsRequest {
  static encode(message: DivRemNativeAmountsRequest, writer: Writer): void {
    const dividend = message.dividend;
    if (dividend !== null) {
      writer.uint32(10);
      writer.fork();
      NativeAmount.encode(dividend, writer);
      writer.ldelim();
    }

    const divisor = message.divisor;
    if (divisor !== null) {
      writer.uint32(18);
      writer.fork();
      NativeAmount.encode(divisor, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): DivRemNativeAmountsRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DivRemNativeAmountsRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.dividend = NativeAmount.decode(reader, reader.uint32());
          break;

        case 2:
          message.divisor = NativeAmount.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  dividend: NativeAmount | null;
  divisor: NativeAmount | null;

  constructor(
    dividend: NativeAmount | null = null,
    divisor: NativeAmount | null = null
  ) {
    this.dividend = dividend;
    this.divisor = divisor;
  }
}

export function encodeDivRemNativeAmountsRequest(
  message: DivRemNativeAmountsRequest
): Uint8Array {
  return Protobuf.encode(message, DivRemNativeAmountsRequest.encode);
}

export function decodeDivRemNativeAmountsRequest(
  buffer: Uint8Array
): DivRemNativeAmountsRequest {
  return Protobuf.decode<DivRemNativeAmountsRequest>(
    buffer,
    DivRemNativeAmountsRequest.decode
  );
}
