// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class FunctionExistsResponse {
  static encode(message: FunctionExistsResponse, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.exists);
  }

  static decode(reader: Reader, length: i32): FunctionExistsResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new FunctionExistsResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.exists = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  exists: bool;

  constructor(exists: bool = false) {
    this.exists = exists;
  }
}

export function encodeFunctionExistsResponse(
  message: FunctionExistsResponse
): Uint8Array {
  return Protobuf.encode(message, FunctionExistsResponse.encode);
}

export function decodeFunctionExistsResponse(
  buffer: Uint8Array
): FunctionExistsResponse {
  return Protobuf.decode<FunctionExistsResponse>(
    buffer,
    FunctionExistsResponse.decode
  );
}
