// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class GetAddressVersionResult {
  static encode(message: GetAddressVersionResult, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.version);
  }

  static decode(reader: Reader, length: i32): GetAddressVersionResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetAddressVersionResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.version = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  version: u64;

  constructor(version: u64 = 0) {
    this.version = version;
  }
}

export function encodeGetAddressVersionResult(
  message: GetAddressVersionResult
): Uint8Array {
  return Protobuf.encode(message, GetAddressVersionResult.encode);
}

export function decodeGetAddressVersionResult(
  buffer: Uint8Array
): GetAddressVersionResult {
  return Protobuf.decode<GetAddressVersionResult>(
    buffer,
    GetAddressVersionResult.decode
  );
}
