// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class GetAddressVersionRequest {
  static encode(message: GetAddressVersionRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.address);
  }

  static decode(reader: Reader, length: i32): GetAddressVersionRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetAddressVersionRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.address = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  address: string;

  constructor(address: string = "") {
    this.address = address;
  }
}

export function encodeGetAddressVersionRequest(
  message: GetAddressVersionRequest
): Uint8Array {
  return Protobuf.encode(message, GetAddressVersionRequest.encode);
}

export function decodeGetAddressVersionRequest(
  buffer: Uint8Array
): GetAddressVersionRequest {
  return Protobuf.decode<GetAddressVersionRequest>(
    buffer,
    GetAddressVersionRequest.decode
  );
}
