// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class GetCallStackRequest {
  static encode(message: GetCallStackRequest, writer: Writer): void {}

  static decode(reader: Reader, length: i32): GetCallStackRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetCallStackRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeGetCallStackRequest(
  message: GetCallStackRequest
): Uint8Array {
  return Protobuf.encode(message, GetCallStackRequest.encode);
}

export function decodeGetCallStackRequest(
  buffer: Uint8Array
): GetCallStackRequest {
  return Protobuf.decode<GetCallStackRequest>(
    buffer,
    GetCallStackRequest.decode
  );
}
