// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class GetCallCoinsRequest {
  static encode(message: GetCallCoinsRequest, writer: Writer): void {}

  static decode(reader: Reader, length: i32): GetCallCoinsRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetCallCoinsRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeGetCallCoinsRequest(
  message: GetCallCoinsRequest
): Uint8Array {
  return Protobuf.encode(message, GetCallCoinsRequest.encode);
}

export function decodeGetCallCoinsRequest(
  buffer: Uint8Array
): GetCallCoinsRequest {
  return Protobuf.decode<GetCallCoinsRequest>(
    buffer,
    GetCallCoinsRequest.decode
  );
}
