// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class GetCurrentPeriodResult {
  static encode(message: GetCurrentPeriodResult, writer: Writer): void {
    writer.uint32(8);
    writer.int64(message.period);
  }

  static decode(reader: Reader, length: i32): GetCurrentPeriodResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetCurrentPeriodResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.period = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  period: i64;

  constructor(period: i64 = 0) {
    this.period = period;
  }
}

export function encodeGetCurrentPeriodResult(
  message: GetCurrentPeriodResult
): Uint8Array {
  return Protobuf.encode(message, GetCurrentPeriodResult.encode);
}

export function decodeGetCurrentPeriodResult(
  buffer: Uint8Array
): GetCurrentPeriodResult {
  return Protobuf.decode<GetCurrentPeriodResult>(
    buffer,
    GetCurrentPeriodResult.decode
  );
}
