// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class GetNativeTimeRequest {
  static encode(message: GetNativeTimeRequest, writer: Writer): void {}

  static decode(reader: Reader, length: i32): GetNativeTimeRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetNativeTimeRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeGetNativeTimeRequest(
  message: GetNativeTimeRequest
): Uint8Array {
  return Protobuf.encode(message, GetNativeTimeRequest.encode);
}

export function decodeGetNativeTimeRequest(
  buffer: Uint8Array
): GetNativeTimeRequest {
  return Protobuf.decode<GetNativeTimeRequest>(
    buffer,
    GetNativeTimeRequest.decode
  );
}
