// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativeTime } from "../../model/v1/NativeTime";

export class GetNativeTimeResult {
  static encode(message: GetNativeTimeResult, writer: Writer): void {
    const time = message.time;
    if (time !== null) {
      writer.uint32(10);
      writer.fork();
      NativeTime.encode(time, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): GetNativeTimeResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetNativeTimeResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.time = NativeTime.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  time: NativeTime | null;

  constructor(time: NativeTime | null = null) {
    this.time = time;
  }
}

export function encodeGetNativeTimeResult(
  message: GetNativeTimeResult
): Uint8Array {
  return Protobuf.encode(message, GetNativeTimeResult.encode);
}

export function decodeGetNativeTimeResult(
  buffer: Uint8Array
): GetNativeTimeResult {
  return Protobuf.decode<GetNativeTimeResult>(
    buffer,
    GetNativeTimeResult.decode
  );
}
