// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { StringValue } from "../../../google/protobuf/StringValue";

export class GetOriginOperationIdResult {
  static encode(message: GetOriginOperationIdResult, writer: Writer): void {
    const operationId = message.operationId;
    if (operationId !== null) {
      writer.uint32(10);
      writer.fork();
      StringValue.encode(operationId, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): GetOriginOperationIdResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetOriginOperationIdResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.operationId = StringValue.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  operationId: StringValue | null;

  constructor(operationId: StringValue | null = null) {
    this.operationId = operationId;
  }
}

export function encodeGetOriginOperationIdResult(
  message: GetOriginOperationIdResult
): Uint8Array {
  return Protobuf.encode(message, GetOriginOperationIdResult.encode);
}

export function decodeGetOriginOperationIdResult(
  buffer: Uint8Array
): GetOriginOperationIdResult {
  return Protobuf.decode<GetOriginOperationIdResult>(
    buffer,
    GetOriginOperationIdResult.decode
  );
}
