// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class GetOriginOperationIdRequest {
  static encode(message: GetOriginOperationIdRequest, writer: Writer): void {}

  static decode(reader: Reader, length: i32): GetOriginOperationIdRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetOriginOperationIdRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeGetOriginOperationIdRequest(
  message: GetOriginOperationIdRequest
): Uint8Array {
  return Protobuf.encode(message, GetOriginOperationIdRequest.encode);
}

export function decodeGetOriginOperationIdRequest(
  buffer: Uint8Array
): GetOriginOperationIdRequest {
  return Protobuf.decode<GetOriginOperationIdRequest>(
    buffer,
    GetOriginOperationIdRequest.decode
  );
}
