// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativeAddress } from "..\\..\\model\\v1\\NativeAddress";

export class GetOwnedAddressesResult {
  static encode(message: GetOwnedAddressesResult, writer: Writer): void {
    const addresses = message.addresses;
    for (let i: i32 = 0; i < addresses.length; ++i) {
      writer.uint32(10);
      writer.fork();
      NativeAddress.encode(addresses[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): GetOwnedAddressesResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetOwnedAddressesResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.addresses.push(NativeAddress.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  addresses: Array<NativeAddress>;

  constructor(addresses: Array<NativeAddress> = []) {
    this.addresses = addresses;
  }
}

export function encodeGetOwnedAddressesResult(
  message: GetOwnedAddressesResult
): Uint8Array {
  return Protobuf.encode(message, GetOwnedAddressesResult.encode);
}

export function decodeGetOwnedAddressesResult(
  buffer: Uint8Array
): GetOwnedAddressesResult {
  return Protobuf.decode<GetOwnedAddressesResult>(
    buffer,
    GetOwnedAddressesResult.decode
  );
}
