// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class GetPubKeyVersionResult {
  static encode(message: GetPubKeyVersionResult, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.version);
  }

  static decode(reader: Reader, length: i32): GetPubKeyVersionResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetPubKeyVersionResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.version = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  version: u64;

  constructor(version: u64 = 0) {
    this.version = version;
  }
}

export function encodeGetPubKeyVersionResult(
  message: GetPubKeyVersionResult
): Uint8Array {
  return Protobuf.encode(message, GetPubKeyVersionResult.encode);
}

export function decodeGetPubKeyVersionResult(
  buffer: Uint8Array
): GetPubKeyVersionResult {
  return Protobuf.decode<GetPubKeyVersionResult>(
    buffer,
    GetPubKeyVersionResult.decode
  );
}
