// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { UInt64Value } from "../../../google/protobuf/UInt64Value";

export class GetPubKeyVersionResult {
  static encode(message: GetPubKeyVersionResult, writer: Writer): void {
    const mandatoryVersion = message.mandatoryVersion;
    if (mandatoryVersion !== null) {
      writer.uint32(10);
      writer.fork();
      UInt64Value.encode(mandatoryVersion, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): GetPubKeyVersionResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetPubKeyVersionResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.mandatoryVersion = UInt64Value.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  mandatoryVersion: UInt64Value | null;

  constructor(mandatoryVersion: UInt64Value | null = null) {
    this.mandatoryVersion = mandatoryVersion;
  }
}

export function encodeGetPubKeyVersionResult(
  message: GetPubKeyVersionResult
): Uint8Array {
  return Protobuf.encode(message, GetPubKeyVersionResult.encode);
}

export function decodeGetPubKeyVersionResult(
  buffer: Uint8Array
): GetPubKeyVersionResult {
  return Protobuf.decode<GetPubKeyVersionResult>(
    buffer,
    GetPubKeyVersionResult.decode
  );
}
