// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class GetRemainingGasResult {
  static encode(message: GetRemainingGasResult, writer: Writer): void {
    writer.uint32(8);
    writer.int64(message.remainingGas);
  }

  static decode(reader: Reader, length: i32): GetRemainingGasResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetRemainingGasResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.remainingGas = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  remainingGas: i64;

  constructor(remainingGas: i64 = 0) {
    this.remainingGas = remainingGas;
  }
}

export function encodeGetRemainingGasResult(
  message: GetRemainingGasResult
): Uint8Array {
  return Protobuf.encode(message, GetRemainingGasResult.encode);
}

export function decodeGetRemainingGasResult(
  buffer: Uint8Array
): GetRemainingGasResult {
  return Protobuf.decode<GetRemainingGasResult>(
    buffer,
    GetRemainingGasResult.decode
  );
}
