// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class GetSignatureVersionRequest {
  static encode(message: GetSignatureVersionRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.signature);
  }

  static decode(reader: Reader, length: i32): GetSignatureVersionRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetSignatureVersionRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.signature = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  signature: string;

  constructor(signature: string = "") {
    this.signature = signature;
  }
}

export function encodeGetSignatureVersionRequest(
  message: GetSignatureVersionRequest
): Uint8Array {
  return Protobuf.encode(message, GetSignatureVersionRequest.encode);
}

export function decodeGetSignatureVersionRequest(
  buffer: Uint8Array
): GetSignatureVersionRequest {
  return Protobuf.decode<GetSignatureVersionRequest>(
    buffer,
    GetSignatureVersionRequest.decode
  );
}
