// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { Address } from "./Address";

export class LocalCallRequest {
  static encode(message: LocalCallRequest, writer: Writer): void {
    const address = message.address;
    if (address !== null) {
      writer.uint32(10);
      writer.fork();
      Address.encode(address, writer);
      writer.ldelim();
    }

    writer.uint32(18);
    writer.string(message.function);

    writer.uint32(26);
    writer.bytes(message.arg);
  }

  static decode(reader: Reader, length: i32): LocalCallRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new LocalCallRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.address = Address.decode(reader, reader.uint32());
          break;

        case 2:
          message.function = reader.string();
          break;

        case 3:
          message.arg = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  address: Address | null;
  function: string;
  arg: Uint8Array;

  constructor(
    address: Address | null = null,
    function_: string = "",
    arg: Uint8Array = new Uint8Array(0)
  ) {
    this.address = address;
    this.function = function_;
    this.arg = arg;
  }
}

export function encodeLocalCallRequest(message: LocalCallRequest): Uint8Array {
  return Protobuf.encode(message, LocalCallRequest.encode);
}

export function decodeLocalCallRequest(buffer: Uint8Array): LocalCallRequest {
  return Protobuf.decode<LocalCallRequest>(buffer, LocalCallRequest.decode);
}
