// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class NativeAddressToStringResult {
  static encode(message: NativeAddressToStringResult, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.convertedAddress);
  }

  static decode(reader: Reader, length: i32): NativeAddressToStringResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NativeAddressToStringResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.convertedAddress = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  convertedAddress: string;

  constructor(convertedAddress: string = "") {
    this.convertedAddress = convertedAddress;
  }
}

export function encodeNativeAddressToStringResult(
  message: NativeAddressToStringResult
): Uint8Array {
  return Protobuf.encode(message, NativeAddressToStringResult.encode);
}

export function decodeNativeAddressToStringResult(
  buffer: Uint8Array
): NativeAddressToStringResult {
  return Protobuf.decode<NativeAddressToStringResult>(
    buffer,
    NativeAddressToStringResult.decode
  );
}
