// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class NativeAmountToStringResult {
  static encode(message: NativeAmountToStringResult, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.convertedAmount);
  }

  static decode(reader: Reader, length: i32): NativeAmountToStringResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NativeAmountToStringResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.convertedAmount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  convertedAmount: string;

  constructor(convertedAmount: string = "") {
    this.convertedAmount = convertedAmount;
  }
}

export function encodeNativeAmountToStringResult(
  message: NativeAmountToStringResult
): Uint8Array {
  return Protobuf.encode(message, NativeAmountToStringResult.encode);
}

export function decodeNativeAmountToStringResult(
  buffer: Uint8Array
): NativeAmountToStringResult {
  return Protobuf.decode<NativeAmountToStringResult>(
    buffer,
    NativeAmountToStringResult.decode
  );
}
