// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class NativeAddressFromStringRequest {
  static encode(message: NativeAddressFromStringRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.toConvert);
  }

  static decode(reader: Reader, length: i32): NativeAddressFromStringRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NativeAddressFromStringRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.toConvert = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  toConvert: string;

  constructor(toConvert: string = "") {
    this.toConvert = toConvert;
  }
}

export function encodeNativeAddressFromStringRequest(
  message: NativeAddressFromStringRequest
): Uint8Array {
  return Protobuf.encode(message, NativeAddressFromStringRequest.encode);
}

export function decodeNativeAddressFromStringRequest(
  buffer: Uint8Array
): NativeAddressFromStringRequest {
  return Protobuf.decode<NativeAddressFromStringRequest>(
    buffer,
    NativeAddressFromStringRequest.decode
  );
}
