// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class NativeHashToStringResult {
  static encode(message: NativeHashToStringResult, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.convertedHash);
  }

  static decode(reader: Reader, length: i32): NativeHashToStringResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NativeHashToStringResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.convertedHash = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  convertedHash: string;

  constructor(convertedHash: string = "") {
    this.convertedHash = convertedHash;
  }
}

export function encodeNativeHashToStringResult(
  message: NativeHashToStringResult
): Uint8Array {
  return Protobuf.encode(message, NativeHashToStringResult.encode);
}

export function decodeNativeHashToStringResult(
  buffer: Uint8Array
): NativeHashToStringResult {
  return Protobuf.decode<NativeHashToStringResult>(
    buffer,
    NativeHashToStringResult.decode
  );
}
