// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class NativeHashFromStringRequest {
  static encode(message: NativeHashFromStringRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.toConvert);
  }

  static decode(reader: Reader, length: i32): NativeHashFromStringRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NativeHashFromStringRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.toConvert = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  toConvert: string;

  constructor(toConvert: string = "") {
    this.toConvert = toConvert;
  }
}

export function encodeNativeHashFromStringRequest(
  message: NativeHashFromStringRequest
): Uint8Array {
  return Protobuf.encode(message, NativeHashFromStringRequest.encode);
}

export function decodeNativeHashFromStringRequest(
  buffer: Uint8Array
): NativeHashFromStringRequest {
  return Protobuf.decode<NativeHashFromStringRequest>(
    buffer,
    NativeHashFromStringRequest.decode
  );
}
