// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativePubKey } from "..\\..\\model\\v1\\NativePubKey";

export class NativePubKeyFromStringResult {
  static encode(message: NativePubKeyFromStringResult, writer: Writer): void {
    const convertedPubkey = message.convertedPubkey;
    if (convertedPubkey !== null) {
      writer.uint32(10);
      writer.fork();
      NativePubKey.encode(convertedPubkey, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): NativePubKeyFromStringResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NativePubKeyFromStringResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.convertedPubkey = NativePubKey.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  convertedPubkey: NativePubKey | null;

  constructor(convertedPubkey: NativePubKey | null = null) {
    this.convertedPubkey = convertedPubkey;
  }
}

export function encodeNativePubKeyFromStringResult(
  message: NativePubKeyFromStringResult
): Uint8Array {
  return Protobuf.encode(message, NativePubKeyFromStringResult.encode);
}

export function decodeNativePubKeyFromStringResult(
  buffer: Uint8Array
): NativePubKeyFromStringResult {
  return Protobuf.decode<NativePubKeyFromStringResult>(
    buffer,
    NativePubKeyFromStringResult.decode
  );
}
