// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class NativeSigToStringResult {
  static encode(message: NativeSigToStringResult, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.convertedSig);
  }

  static decode(reader: Reader, length: i32): NativeSigToStringResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NativeSigToStringResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.convertedSig = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  convertedSig: string;

  constructor(convertedSig: string = "") {
    this.convertedSig = convertedSig;
  }
}

export function encodeNativeSigToStringResult(
  message: NativeSigToStringResult
): Uint8Array {
  return Protobuf.encode(message, NativeSigToStringResult.encode);
}

export function decodeNativeSigToStringResult(
  buffer: Uint8Array
): NativeSigToStringResult {
  return Protobuf.decode<NativeSigToStringResult>(
    buffer,
    NativeSigToStringResult.decode
  );
}
