// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.22.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class PrintResult {
  static encode(message: PrintResult, writer: Writer): void {}

  static decode(reader: Reader, length: i32): PrintResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PrintResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodePrintResult(message: PrintResult): Uint8Array {
  return Protobuf.encode(message, PrintResult.encode);
}

export function decodePrintResult(buffer: Uint8Array): PrintResult {
  return Protobuf.decode<PrintResult>(buffer, PrintResult.decode);
}
