// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class PrintRequest {
  static encode(message: PrintRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.message);
  }

  static decode(reader: Reader, length: i32): PrintRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PrintRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.message = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  message: string;

  constructor(message: string = "") {
    this.message = message;
  }
}

export function encodePrintRequest(message: PrintRequest): Uint8Array {
  return Protobuf.encode(message, PrintRequest.encode);
}

export function decodePrintRequest(buffer: Uint8Array): PrintRequest {
  return Protobuf.decode<PrintRequest>(buffer, PrintRequest.decode);
}
