// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class ProcessExitRequest {
  static encode(message: ProcessExitRequest, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.code);
  }

  static decode(reader: Reader, length: i32): ProcessExitRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ProcessExitRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.code = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  code: i32;

  constructor(code: i32 = 0) {
    this.code = code;
  }
}

export function encodeProcessExitRequest(
  message: ProcessExitRequest
): Uint8Array {
  return Protobuf.encode(message, ProcessExitRequest.encode);
}

export function decodeProcessExitRequest(
  buffer: Uint8Array
): ProcessExitRequest {
  return Protobuf.decode<ProcessExitRequest>(buffer, ProcessExitRequest.decode);
}
