// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class SeedResult {
  static encode(message: SeedResult, writer: Writer): void {
    writer.uint32(9);
    writer.double(message.seed);
  }

  static decode(reader: Reader, length: i32): SeedResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SeedResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.seed = reader.double();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  seed: f64;

  constructor(seed: f64 = 0.0) {
    this.seed = seed;
  }
}

export function encodeSeedResult(message: SeedResult): Uint8Array {
  return Protobuf.encode(message, SeedResult.encode);
}

export function decodeSeedResult(buffer: Uint8Array): SeedResult {
  return Protobuf.decode<SeedResult>(buffer, SeedResult.decode);
}
