// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class SetBytecodeResult {
  static encode(message: SetBytecodeResult, writer: Writer): void {}

  static decode(reader: Reader, length: i32): SetBytecodeResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SetBytecodeResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeSetBytecodeResult(
  message: SetBytecodeResult
): Uint8Array {
  return Protobuf.encode(message, SetBytecodeResult.encode);
}

export function decodeSetBytecodeResult(buffer: Uint8Array): SetBytecodeResult {
  return Protobuf.decode<SetBytecodeResult>(buffer, SetBytecodeResult.decode);
}
