// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { StringValue } from "../../../google/protobuf/StringValue";

export class SetBytecodeRequest {
  static encode(message: SetBytecodeRequest, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.bytecode);

    const optionalAddress = message.optionalAddress;
    if (optionalAddress !== null) {
      writer.uint32(18);
      writer.fork();
      StringValue.encode(optionalAddress, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): SetBytecodeRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SetBytecodeRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.bytecode = reader.bytes();
          break;

        case 2:
          message.optionalAddress = StringValue.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  bytecode: Uint8Array;
  optionalAddress: StringValue | null;

  constructor(
    bytecode: Uint8Array = new Uint8Array(0),
    optionalAddress: StringValue | null = null
  ) {
    this.bytecode = bytecode;
    this.optionalAddress = optionalAddress;
  }
}

export function encodeSetBytecodeRequest(
  message: SetBytecodeRequest
): Uint8Array {
  return Protobuf.encode(message, SetBytecodeRequest.encode);
}

export function decodeSetBytecodeRequest(
  buffer: Uint8Array
): SetBytecodeRequest {
  return Protobuf.decode<SetBytecodeRequest>(buffer, SetBytecodeRequest.decode);
}
