// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class SetDataResult {
  static encode(message: SetDataResult, writer: Writer): void {}

  static decode(reader: Reader, length: i32): SetDataResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SetDataResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeSetDataResult(message: SetDataResult): Uint8Array {
  return Protobuf.encode(message, SetDataResult.encode);
}

export function decodeSetDataResult(buffer: Uint8Array): SetDataResult {
  return Protobuf.decode<SetDataResult>(buffer, SetDataResult.decode);
}
