// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class SetDsValueResult {
  static encode(message: SetDsValueResult, writer: Writer): void {}

  static decode(reader: Reader, length: i32): SetDsValueResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SetDsValueResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeSetDsValueResult(message: SetDsValueResult): Uint8Array {
  return Protobuf.encode(message, SetDsValueResult.encode);
}

export function decodeSetDsValueResult(buffer: Uint8Array): SetDsValueResult {
  return Protobuf.decode<SetDsValueResult>(buffer, SetDsValueResult.decode);
}
