// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class TraceResult {
  static encode(message: TraceResult, writer: Writer): void {}

  static decode(reader: Reader, length: i32): TraceResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TraceResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeTraceResult(message: TraceResult): Uint8Array {
  return Protobuf.encode(message, TraceResult.encode);
}

export function decodeTraceResult(buffer: Uint8Array): TraceResult {
  return Protobuf.decode<TraceResult>(buffer, TraceResult.decode);
}
