// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NativeAmount } from "../../model/v1/NativeAmount";
import { StringValue } from "../../../google/protobuf/StringValue";

export class TransferCoinsRequest {
  static encode(message: TransferCoinsRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.targetAddress);

    const amountToTransfer = message.amountToTransfer;
    if (amountToTransfer !== null) {
      writer.uint32(18);
      writer.fork();
      NativeAmount.encode(amountToTransfer, writer);
      writer.ldelim();
    }

    const senderAddress = message.senderAddress;
    if (senderAddress !== null) {
      writer.uint32(26);
      writer.fork();
      StringValue.encode(senderAddress, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): TransferCoinsRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TransferCoinsRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.targetAddress = reader.string();
          break;

        case 2:
          message.amountToTransfer = NativeAmount.decode(
            reader,
            reader.uint32()
          );
          break;

        case 3:
          message.senderAddress = StringValue.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  targetAddress: string;
  amountToTransfer: NativeAmount | null;
  senderAddress: StringValue | null;

  constructor(
    targetAddress: string = "",
    amountToTransfer: NativeAmount | null = null,
    senderAddress: StringValue | null = null
  ) {
    this.targetAddress = targetAddress;
    this.amountToTransfer = amountToTransfer;
    this.senderAddress = senderAddress;
  }
}

export function encodeTransferCoinsRequest(
  message: TransferCoinsRequest
): Uint8Array {
  return Protobuf.encode(message, TransferCoinsRequest.encode);
}

export function decodeTransferCoinsRequest(
  buffer: Uint8Array
): TransferCoinsRequest {
  return Protobuf.decode<TransferCoinsRequest>(
    buffer,
    TransferCoinsRequest.decode
  );
}
