// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class UnsafeRandomResult {
  static encode(message: UnsafeRandomResult, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.randomBytes);
  }

  static decode(reader: Reader, length: i32): UnsafeRandomResult {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new UnsafeRandomResult();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.randomBytes = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  randomBytes: Uint8Array;

  constructor(randomBytes: Uint8Array = new Uint8Array(0)) {
    this.randomBytes = randomBytes;
  }
}

export function encodeUnsafeRandomResult(
  message: UnsafeRandomResult
): Uint8Array {
  return Protobuf.encode(message, UnsafeRandomResult.encode);
}

export function decodeUnsafeRandomResult(
  buffer: Uint8Array
): UnsafeRandomResult {
  return Protobuf.decode<UnsafeRandomResult>(buffer, UnsafeRandomResult.decode);
}
