// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class UnsafeRandomRequest {
  static encode(message: UnsafeRandomRequest, writer: Writer): void {}

  static decode(reader: Reader, length: i32): UnsafeRandomRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new UnsafeRandomRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeUnsafeRandomRequest(
  message: UnsafeRandomRequest
): Uint8Array {
  return Protobuf.encode(message, UnsafeRandomRequest.encode);
}

export function decodeUnsafeRandomRequest(
  buffer: Uint8Array
): UnsafeRandomRequest {
  return Protobuf.decode<UnsafeRandomRequest>(
    buffer,
    UnsafeRandomRequest.decode
  );
}
