// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class LeftLower {
  static encode(message: LeftLower, writer: Writer): void {}

  static decode(reader: Reader, length: i32): LeftLower {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new LeftLower();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeLeftLower(message: LeftLower): Uint8Array {
  return Protobuf.encode(message, LeftLower.encode);
}

export function decodeLeftLower(buffer: Uint8Array): LeftLower {
  return Protobuf.decode<LeftLower>(buffer, LeftLower.decode);
}
