// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.2

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class Equal {
  static encode(message: Equal, writer: Writer): void {}

  static decode(reader: Reader, length: i32): Equal {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Equal();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeEqual(message: Equal): Uint8Array {
  return Protobuf.encode(message, Equal.encode);
}

export function decodeEqual(buffer: Uint8Array): Equal {
  return Protobuf.decode<Equal>(buffer, Equal.decode);
}
